/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.myconcordia.comp5541.scribr;

import ca.myconcordia.comp5541.scribr.db.DatabaseConnection;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileWriter;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.util.Scanner;
import java.io.FileReader;

/**
 *
 * @author sarsingh
 */
public class MainUI extends javax.swing.JFrame {

    private static Connection connection = DatabaseConnection.getConnection();

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel_SideMenu = new javax.swing.JPanel();
        jLabel_RecentEdits = new javax.swing.JLabel();
        jPanel_WordEdits = new javax.swing.JPanel();
        jLabel_Words = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jPanel_SentenceEdits = new javax.swing.JPanel();
        jLabel_Sentences = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jPanel_ParagraphEdits = new javax.swing.JPanel();
        jLabel_Paragraphs = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jPanel_SectionEdits = new javax.swing.JPanel();
        jLabel_Sections = new javax.swing.JLabel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jPanel_ChapterEdits = new javax.swing.JPanel();
        jLabel_Sections1 = new javax.swing.JLabel();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        FileMenuNew = new javax.swing.JMenuItem();
        FileMenuOpen = new javax.swing.JMenuItem();
        FileMenuSave = new javax.swing.JMenuItem();
        FileMenuQuit = new javax.swing.JMenuItem();
        InsertMenu = new javax.swing.JMenu();
        InsertMenuNewChapter = new javax.swing.JMenuItem();
        InsertMenuNewSection = new javax.swing.JMenuItem();
        UndoMenu = new javax.swing.JMenu();
        UndoMenuSelectedEdits = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        UndoMenuLastChapterEdit = new javax.swing.JMenuItem();
        UndoMenuLastSectionEdit = new javax.swing.JMenuItem();
        UndoMenuLastParagraphEdit = new javax.swing.JMenuItem();
        UndoMenuLastSentenceEdit = new javax.swing.JMenuItem();
        UndoMenuLastWordEdit = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        UndoMenuAllChapterEdits = new javax.swing.JMenuItem();
        UndoMenuAllSectionEdits = new javax.swing.JMenuItem();
        UndoMenuAllParagraphEdits = new javax.swing.JMenuItem();
        UndoMenuAllSentenceEdits = new javax.swing.JMenuItem();
        UndoMenuAllWordEdits = new javax.swing.JMenuItem();
        DeleteMenu = new javax.swing.JMenu();
        DeleteMenuSelectedEdits = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        DeleteMenuAllChapterEdits = new javax.swing.JMenuItem();
        DeleteMenuAllSectionEdits = new javax.swing.JMenuItem();
        DeleteMenuAllParagraphEdits = new javax.swing.JMenuItem();
        DeleteMenuAllSentenceEdits = new javax.swing.JMenuItem();
        DeleteMenuAllWordEdits = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        HelpMenuScribrManual = new javax.swing.JMenuItem();
        HelpMenuFAQ = new javax.swing.JMenuItem();
        HelpMenuReportBug = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scribr");

        jTextArea.setColumns(20);
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jLabel_RecentEdits.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_RecentEdits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_RecentEdits.setText("Recent Edits");

        jLabel_Words.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Words.setText("Words");

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox1");

        jCheckBox3.setText("jCheckBox1");

        jCheckBox4.setText("jCheckBox1");

        jCheckBox5.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel_WordEditsLayout = new javax.swing.GroupLayout(jPanel_WordEdits);
        jPanel_WordEdits.setLayout(jPanel_WordEditsLayout);
        jPanel_WordEditsLayout.setHorizontalGroup(
            jPanel_WordEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WordEditsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_WordEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_WordEditsLayout.createSequentialGroup()
                        .addComponent(jLabel_Words)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_WordEditsLayout.createSequentialGroup()
                        .addGroup(jPanel_WordEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel_WordEditsLayout.setVerticalGroup(
            jPanel_WordEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_WordEditsLayout.createSequentialGroup()
                .addComponent(jLabel_Words)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel_Sentences.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Sentences.setText("Sentences");

        jCheckBox6.setText("jCheckBox1");

        jCheckBox7.setText("jCheckBox1");

        jCheckBox8.setText("jCheckBox1");

        jCheckBox9.setText("jCheckBox1");

        jCheckBox10.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel_SentenceEditsLayout = new javax.swing.GroupLayout(jPanel_SentenceEdits);
        jPanel_SentenceEdits.setLayout(jPanel_SentenceEditsLayout);
        jPanel_SentenceEditsLayout.setHorizontalGroup(
            jPanel_SentenceEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SentenceEditsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SentenceEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SentenceEditsLayout.createSequentialGroup()
                        .addComponent(jLabel_Sentences)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_SentenceEditsLayout.createSequentialGroup()
                        .addGroup(jPanel_SentenceEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel_SentenceEditsLayout.setVerticalGroup(
            jPanel_SentenceEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SentenceEditsLayout.createSequentialGroup()
                .addComponent(jLabel_Sentences)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox10)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel_Paragraphs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Paragraphs.setText("Paragraphs");

        jCheckBox11.setText("jCheckBox1");

        jCheckBox12.setText("jCheckBox1");

        jCheckBox13.setText("jCheckBox1");

        jCheckBox14.setText("jCheckBox1");

        jCheckBox15.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel_ParagraphEditsLayout = new javax.swing.GroupLayout(jPanel_ParagraphEdits);
        jPanel_ParagraphEdits.setLayout(jPanel_ParagraphEditsLayout);
        jPanel_ParagraphEditsLayout.setHorizontalGroup(
            jPanel_ParagraphEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ParagraphEditsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ParagraphEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ParagraphEditsLayout.createSequentialGroup()
                        .addComponent(jLabel_Paragraphs)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_ParagraphEditsLayout.createSequentialGroup()
                        .addGroup(jPanel_ParagraphEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                            .addComponent(jCheckBox11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        jPanel_ParagraphEditsLayout.setVerticalGroup(
            jPanel_ParagraphEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ParagraphEditsLayout.createSequentialGroup()
                .addComponent(jLabel_Paragraphs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_Sections.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Sections.setText("Sections");

        jCheckBox21.setText("jCheckBox1");

        jCheckBox22.setText("jCheckBox1");

        jCheckBox23.setText("jCheckBox1");

        jCheckBox24.setText("jCheckBox1");

        jCheckBox25.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel_SectionEditsLayout = new javax.swing.GroupLayout(jPanel_SectionEdits);
        jPanel_SectionEdits.setLayout(jPanel_SectionEditsLayout);
        jPanel_SectionEditsLayout.setHorizontalGroup(
            jPanel_SectionEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SectionEditsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SectionEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SectionEditsLayout.createSequentialGroup()
                        .addComponent(jLabel_Sections)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_SectionEditsLayout.createSequentialGroup()
                        .addGroup(jPanel_SectionEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel_SectionEditsLayout.setVerticalGroup(
            jPanel_SectionEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SectionEditsLayout.createSequentialGroup()
                .addComponent(jLabel_Sections)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox25)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel_Sections1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Sections1.setText("Chapters");

        jCheckBox31.setText("jCheckBox1");

        jCheckBox32.setText("jCheckBox1");

        jCheckBox33.setText("jCheckBox1");

        jCheckBox34.setText("jCheckBox1");

        jCheckBox35.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel_ChapterEditsLayout = new javax.swing.GroupLayout(jPanel_ChapterEdits);
        jPanel_ChapterEdits.setLayout(jPanel_ChapterEditsLayout);
        jPanel_ChapterEditsLayout.setHorizontalGroup(
            jPanel_ChapterEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChapterEditsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ChapterEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ChapterEditsLayout.createSequentialGroup()
                        .addComponent(jLabel_Sections1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_ChapterEditsLayout.createSequentialGroup()
                        .addGroup(jPanel_ChapterEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel_ChapterEditsLayout.setVerticalGroup(
            jPanel_ChapterEditsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChapterEditsLayout.createSequentialGroup()
                .addComponent(jLabel_Sections1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox35)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_SideMenuLayout = new javax.swing.GroupLayout(jPanel_SideMenu);
        jPanel_SideMenu.setLayout(jPanel_SideMenuLayout);
        jPanel_SideMenuLayout.setHorizontalGroup(
            jPanel_SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_WordEdits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_SentenceEdits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_ParagraphEdits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_SectionEdits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_SideMenuLayout.createSequentialGroup()
                .addComponent(jLabel_RecentEdits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel_ChapterEdits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_SideMenuLayout.setVerticalGroup(
            jPanel_SideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SideMenuLayout.createSequentialGroup()
                .addComponent(jLabel_RecentEdits, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_WordEdits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_SentenceEdits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_ParagraphEdits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_SectionEdits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_ChapterEdits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel_SideMenu);

        FileMenu.setText("File");

        FileMenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuNew.setText("New");
        FileMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuNewActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuNew);

        FileMenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuOpen.setText("Open");
        FileMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuOpenActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuOpen);

        FileMenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuSave.setText("Save");
        FileMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuSaveActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuSave);

        FileMenuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuQuit.setText("Quit");
        FileMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuQuitActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuQuit);

        MainMenuBar.add(FileMenu);

        InsertMenu.setText("Insert");

        InsertMenuNewChapter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        InsertMenuNewChapter.setText("New Chapter");
        InsertMenuNewChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMenuNewChapterActionPerformed(evt);
            }
        });
        InsertMenu.add(InsertMenuNewChapter);

        InsertMenuNewSection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        InsertMenuNewSection.setText("New Section");
        InsertMenu.add(InsertMenuNewSection);

        MainMenuBar.add(InsertMenu);

        UndoMenu.setText("Undo");

        UndoMenuSelectedEdits.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuSelectedEdits.setText("Selected Edits");
        UndoMenuSelectedEdits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoMenuSelectedEditsActionPerformed(evt);
            }
        });
        UndoMenu.add(UndoMenuSelectedEdits);
        UndoMenu.add(jSeparator1);

        UndoMenuLastChapterEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastChapterEdit.setText("Last Chapter Edit");
        UndoMenuLastChapterEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoMenuLastChapterEditActionPerformed(evt);
            }
        });
        UndoMenu.add(UndoMenuLastChapterEdit);

        UndoMenuLastSectionEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastSectionEdit.setText("Last Section Edit");
        UndoMenu.add(UndoMenuLastSectionEdit);

        UndoMenuLastParagraphEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastParagraphEdit.setText("Last Paragraph Edit");
        UndoMenu.add(UndoMenuLastParagraphEdit);

        UndoMenuLastSentenceEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastSentenceEdit.setText("Last Sentence Edit");
        UndoMenu.add(UndoMenuLastSentenceEdit);

        UndoMenuLastWordEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastWordEdit.setText("Last Word Edit");
        UndoMenu.add(UndoMenuLastWordEdit);
        UndoMenu.add(jSeparator2);

        UndoMenuAllChapterEdits.setText("All Chapter Edits");
        UndoMenu.add(UndoMenuAllChapterEdits);

        UndoMenuAllSectionEdits.setText("All Section Edits");
        UndoMenu.add(UndoMenuAllSectionEdits);

        UndoMenuAllParagraphEdits.setText("All Paragraph Edits");
        UndoMenu.add(UndoMenuAllParagraphEdits);

        UndoMenuAllSentenceEdits.setText("All Sentence Edits");
        UndoMenu.add(UndoMenuAllSentenceEdits);

        UndoMenuAllWordEdits.setText("All Word Edits");
        UndoMenu.add(UndoMenuAllWordEdits);

        MainMenuBar.add(UndoMenu);

        DeleteMenu.setText("Delete");

        DeleteMenuSelectedEdits.setText("Selected Edits");
        DeleteMenuSelectedEdits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMenuSelectedEditsActionPerformed(evt);
            }
        });
        DeleteMenu.add(DeleteMenuSelectedEdits);
        DeleteMenu.add(jSeparator3);

        DeleteMenuAllChapterEdits.setText("All Chapter Edits");
        DeleteMenu.add(DeleteMenuAllChapterEdits);

        DeleteMenuAllSectionEdits.setText("All Section Edits");
        DeleteMenu.add(DeleteMenuAllSectionEdits);

        DeleteMenuAllParagraphEdits.setText("All Paragraph Edits");
        DeleteMenu.add(DeleteMenuAllParagraphEdits);

        DeleteMenuAllSentenceEdits.setText("All Sentence Edits");
        DeleteMenu.add(DeleteMenuAllSentenceEdits);

        DeleteMenuAllWordEdits.setText("All Word Edits");
        DeleteMenu.add(DeleteMenuAllWordEdits);

        MainMenuBar.add(DeleteMenu);

        HelpMenu.setText("Help");

        HelpMenuScribrManual.setText("Scribr Manual");
        HelpMenu.add(HelpMenuScribrManual);

        HelpMenuFAQ.setText("FAQ");
        HelpMenu.add(HelpMenuFAQ);

        HelpMenuReportBug.setText("Report A Bug");
        HelpMenu.add(HelpMenuReportBug);

        MainMenuBar.add(HelpMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 707, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuNewActionPerformed
        jTextArea.setText("");

    }//GEN-LAST:event_FileMenuNewActionPerformed

    private void FileMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FileMenuQuitActionPerformed

    private void FileMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuSaveActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose destination.");
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        jfc.showSaveDialog(null);
        try {
            File f = new File(jfc.getSelectedFile().getAbsolutePath());
            FileWriter out = new FileWriter(f);
            out.write(jTextArea.getText());
            out.close();
        } catch (FileNotFoundException ex) {
            Component f = null;
            JOptionPane.showMessageDialog(f, "File not found.");
        } catch (IOException ex) {
            Component f = null;
            JOptionPane.showMessageDialog(f, "Error.");
        }
    }//GEN-LAST:event_FileMenuSaveActionPerformed

    private void InsertMenuNewChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMenuNewChapterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertMenuNewChapterActionPerformed

    private void UndoMenuSelectedEditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoMenuSelectedEditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoMenuSelectedEditsActionPerformed

    private void UndoMenuLastChapterEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoMenuLastChapterEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoMenuLastChapterEditActionPerformed

    private void DeleteMenuSelectedEditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMenuSelectedEditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMenuSelectedEditsActionPerformed

    private void FileMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuOpenActionPerformed
        String ingest = null;
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose destination.");
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int returnValue = jfc.showOpenDialog(null);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File f = new File(jfc.getSelectedFile().getAbsolutePath());
            try {
                FileReader read = new FileReader(f);
                Scanner scan = new Scanner(read);
                while (scan.hasNextLine()) {
                    String line = scan.nextLine() + "\n";
                    ingest = ingest + line;
                }
                jTextArea.setText(ingest);
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_FileMenuOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DeleteMenu;
    private javax.swing.JMenuItem DeleteMenuAllChapterEdits;
    private javax.swing.JMenuItem DeleteMenuAllParagraphEdits;
    private javax.swing.JMenuItem DeleteMenuAllSectionEdits;
    private javax.swing.JMenuItem DeleteMenuAllSentenceEdits;
    private javax.swing.JMenuItem DeleteMenuAllWordEdits;
    private javax.swing.JMenuItem DeleteMenuSelectedEdits;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem FileMenuNew;
    private javax.swing.JMenuItem FileMenuOpen;
    private javax.swing.JMenuItem FileMenuQuit;
    private javax.swing.JMenuItem FileMenuSave;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem HelpMenuFAQ;
    private javax.swing.JMenuItem HelpMenuReportBug;
    private javax.swing.JMenuItem HelpMenuScribrManual;
    private javax.swing.JMenu InsertMenu;
    private javax.swing.JMenuItem InsertMenuNewChapter;
    private javax.swing.JMenuItem InsertMenuNewSection;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenu UndoMenu;
    private javax.swing.JMenuItem UndoMenuAllChapterEdits;
    private javax.swing.JMenuItem UndoMenuAllParagraphEdits;
    private javax.swing.JMenuItem UndoMenuAllSectionEdits;
    private javax.swing.JMenuItem UndoMenuAllSentenceEdits;
    private javax.swing.JMenuItem UndoMenuAllWordEdits;
    private javax.swing.JMenuItem UndoMenuLastChapterEdit;
    private javax.swing.JMenuItem UndoMenuLastParagraphEdit;
    private javax.swing.JMenuItem UndoMenuLastSectionEdit;
    private javax.swing.JMenuItem UndoMenuLastSentenceEdit;
    private javax.swing.JMenuItem UndoMenuLastWordEdit;
    private javax.swing.JMenuItem UndoMenuSelectedEdits;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel_Paragraphs;
    private javax.swing.JLabel jLabel_RecentEdits;
    private javax.swing.JLabel jLabel_Sections;
    private javax.swing.JLabel jLabel_Sections1;
    private javax.swing.JLabel jLabel_Sentences;
    private javax.swing.JLabel jLabel_Words;
    private javax.swing.JPanel jPanel_ChapterEdits;
    private javax.swing.JPanel jPanel_ParagraphEdits;
    private javax.swing.JPanel jPanel_SectionEdits;
    private javax.swing.JPanel jPanel_SentenceEdits;
    private javax.swing.JPanel jPanel_SideMenu;
    private javax.swing.JPanel jPanel_WordEdits;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
