/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.myconcordia.comp5541.scribr;

import ca.myconcordia.comp5541.scribr.db.DatabaseConnection;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileWriter;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Scanner;
import java.io.FileReader;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author sarsingh
 */
public class MainUI extends javax.swing.JFrame {

    private static Connection connection;

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        ComboBoxWords = new javax.swing.JComboBox<>();
        ComboBoxSentences = new javax.swing.JComboBox<>();
        ComboBoxParagraphs = new javax.swing.JComboBox<>();
        ComboBoxPages = new javax.swing.JComboBox<>();
        ComboBoxSections = new javax.swing.JComboBox<>();
        ComboBoxChapters = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        FileMenuNew = new javax.swing.JMenuItem();
        FileMenuOpen = new javax.swing.JMenuItem();
        FileMenuSave = new javax.swing.JMenuItem();
        FileMenuQuit = new javax.swing.JMenuItem();
        InsertMenu = new javax.swing.JMenu();
        InsertMenuNewChapter = new javax.swing.JMenuItem();
        InsertMenuNewSection = new javax.swing.JMenuItem();
        InsertMenuNewSubsection = new javax.swing.JMenuItem();
        InsertMenuNewParagraph = new javax.swing.JMenuItem();
        UndoMenu = new javax.swing.JMenu();
        UndoMenuSelectedEdits = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        UndoMenuLastChapterEdit = new javax.swing.JMenuItem();
        UndoMenuLastSectionEdit = new javax.swing.JMenuItem();
        UndoMenuLastSubsectionEdit = new javax.swing.JMenuItem();
        UndoMenuLastParagraphEdit = new javax.swing.JMenuItem();
        UndoMenuLastSentenceEdit = new javax.swing.JMenuItem();
        UndoMenuLastWordEdit = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        UndoMenuAllChapterEdits = new javax.swing.JMenuItem();
        UndoMenuAllSectionEdits = new javax.swing.JMenuItem();
        UndoMenuAllPageEdits = new javax.swing.JMenuItem();
        UndoMenuAllParagraphEdits = new javax.swing.JMenuItem();
        UndoMenuAllSentenceEdits = new javax.swing.JMenuItem();
        UndoMenuAllWordEdits = new javax.swing.JMenuItem();
        DeleteMenu = new javax.swing.JMenu();
        DeleteMenuSelectedEdits = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        DeleteMenuAllChapterEdits = new javax.swing.JMenuItem();
        DeleteMenuAllSectionEdits = new javax.swing.JMenuItem();
        DeleteMenuAllSubsectionEdits = new javax.swing.JMenuItem();
        DeleteMenuAllParagraphEdits = new javax.swing.JMenuItem();
        DeleteMenuAllSentenceEdits = new javax.swing.JMenuItem();
        DeleteMenuAllWordEdits = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        HelpMenuScribrManual = new javax.swing.JMenuItem();
        HelpMenuFAQ = new javax.swing.JMenuItem();
        HelpMenuReportBug = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scribr");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        ComboBoxWords.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Words" }));
        ComboBoxWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxWordsActionPerformed(evt);
            }
        });

        ComboBoxSentences.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentences" }));

        ComboBoxParagraphs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paragraphs" }));

        ComboBoxPages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pages" }));

        ComboBoxSections.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sections" }));

        ComboBoxChapters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chapters" }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recent Edits");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxWords, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxSentences, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxParagraphs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxPages, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxSections, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxChapters, 0, 130, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(ComboBoxWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxSentences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxParagraphs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxSections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxChapters)
                .addGap(385, 385, 385))
        );

        FileMenu.setText("File");

        FileMenuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuNew.setText("New");
        FileMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuNewActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuNew);

        FileMenuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuOpen.setText("Open");
        FileMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuOpenActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuOpen);

        FileMenuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuSave.setText("Save");
        FileMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuSaveActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuSave);

        FileMenuQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FileMenuQuit.setText("Quit");
        FileMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuQuitActionPerformed(evt);
            }
        });
        FileMenu.add(FileMenuQuit);

        MainMenuBar.add(FileMenu);

        InsertMenu.setText("Insert");

        InsertMenuNewChapter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        InsertMenuNewChapter.setText("New Chapter");
        InsertMenuNewChapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMenuNewChapterActionPerformed(evt);
            }
        });
        InsertMenu.add(InsertMenuNewChapter);

        InsertMenuNewSection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        InsertMenuNewSection.setText("New Section");
        InsertMenu.add(InsertMenuNewSection);

        InsertMenuNewSubsection.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        InsertMenuNewSubsection.setText("New Subsection");
        InsertMenuNewSubsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMenuNewSubsectionActionPerformed(evt);
            }
        });
        InsertMenu.add(InsertMenuNewSubsection);

        InsertMenuNewParagraph.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        InsertMenuNewParagraph.setText("New Paragraph");
        InsertMenuNewParagraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertMenuNewParagraphActionPerformed(evt);
            }
        });
        InsertMenu.add(InsertMenuNewParagraph);

        MainMenuBar.add(InsertMenu);

        UndoMenu.setText("Undo");

        UndoMenuSelectedEdits.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuSelectedEdits.setText("Selected Edits");
        UndoMenuSelectedEdits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoMenuSelectedEditsActionPerformed(evt);
            }
        });
        UndoMenu.add(UndoMenuSelectedEdits);
        UndoMenu.add(jSeparator1);

        UndoMenuLastChapterEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastChapterEdit.setText("Last Chapter Edit");
        UndoMenuLastChapterEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoMenuLastChapterEditActionPerformed(evt);
            }
        });
        UndoMenu.add(UndoMenuLastChapterEdit);

        UndoMenuLastSectionEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastSectionEdit.setText("Last Section Edit");
        UndoMenu.add(UndoMenuLastSectionEdit);

        UndoMenuLastSubsectionEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastSubsectionEdit.setText("Last Subsection Edit");
        UndoMenu.add(UndoMenuLastSubsectionEdit);

        UndoMenuLastParagraphEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastParagraphEdit.setText("Last Paragraph Edit");
        UndoMenu.add(UndoMenuLastParagraphEdit);

        UndoMenuLastSentenceEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastSentenceEdit.setText("Last Sentence Edit");
        UndoMenu.add(UndoMenuLastSentenceEdit);

        UndoMenuLastWordEdit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        UndoMenuLastWordEdit.setText("Last Word Edit");
        UndoMenu.add(UndoMenuLastWordEdit);
        UndoMenu.add(jSeparator2);

        UndoMenuAllChapterEdits.setText("All Chapter Edits");
        UndoMenu.add(UndoMenuAllChapterEdits);

        UndoMenuAllSectionEdits.setText("All Section Edits");
        UndoMenu.add(UndoMenuAllSectionEdits);

        UndoMenuAllPageEdits.setText("All Page Edits");
        UndoMenu.add(UndoMenuAllPageEdits);

        UndoMenuAllParagraphEdits.setText("All Paragraph Edits");
        UndoMenu.add(UndoMenuAllParagraphEdits);

        UndoMenuAllSentenceEdits.setText("All Sentence Edits");
        UndoMenu.add(UndoMenuAllSentenceEdits);

        UndoMenuAllWordEdits.setText("All Word Edits");
        UndoMenu.add(UndoMenuAllWordEdits);

        MainMenuBar.add(UndoMenu);

        DeleteMenu.setText("Delete");

        DeleteMenuSelectedEdits.setText("Selected Edits");
        DeleteMenuSelectedEdits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMenuSelectedEditsActionPerformed(evt);
            }
        });
        DeleteMenu.add(DeleteMenuSelectedEdits);
        DeleteMenu.add(jSeparator3);

        DeleteMenuAllChapterEdits.setText("All Chapter Edits");
        DeleteMenu.add(DeleteMenuAllChapterEdits);

        DeleteMenuAllSectionEdits.setText("All Section Edits");
        DeleteMenu.add(DeleteMenuAllSectionEdits);

        DeleteMenuAllSubsectionEdits.setText("All Subsection Edits");
        DeleteMenu.add(DeleteMenuAllSubsectionEdits);

        DeleteMenuAllParagraphEdits.setText("All Paragraph Edits");
        DeleteMenu.add(DeleteMenuAllParagraphEdits);

        DeleteMenuAllSentenceEdits.setText("All Sentence Edits");
        DeleteMenu.add(DeleteMenuAllSentenceEdits);

        DeleteMenuAllWordEdits.setText("All Word Edits");
        DeleteMenu.add(DeleteMenuAllWordEdits);

        MainMenuBar.add(DeleteMenu);

        HelpMenu.setText("Help");

        HelpMenuScribrManual.setText("Scribr Manual");
        HelpMenu.add(HelpMenuScribrManual);

        HelpMenuFAQ.setText("FAQ");
        HelpMenu.add(HelpMenuFAQ);

        HelpMenuReportBug.setText("Report A Bug");
        HelpMenu.add(HelpMenuReportBug);

        MainMenuBar.add(HelpMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void databaseNoReturnValue(Connection conn, String query){
                
        try (Statement stmt = conn.createStatement();) {
            stmt.executeUpdate(query);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void FileMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuNewActionPerformed
        jTextArea1.setText("");

    }//GEN-LAST:event_FileMenuNewActionPerformed

    private void FileMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_FileMenuQuitActionPerformed

    private void FileMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuSaveActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose destination.");
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        jfc.showSaveDialog(null);
        try {
            File f = new File(jfc.getSelectedFile().getAbsolutePath());
            FileWriter out = new FileWriter(f);
            out.write(jTextArea1.getText());
            out.close();
        } catch (FileNotFoundException ex) {
            Component f = null;
            JOptionPane.showMessageDialog(f, "File not found.");
        } catch (IOException ex) {
            Component f = null;
            JOptionPane.showMessageDialog(f, "Error.");
        }
    }//GEN-LAST:event_FileMenuSaveActionPerformed

    private void InsertMenuNewChapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMenuNewChapterActionPerformed
        // TODO add your handling code here:
        String s = jTextArea1.getSelectedText();
        System.out.println(s);
    }//GEN-LAST:event_InsertMenuNewChapterActionPerformed

    private void InsertMenuNewSubsectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMenuNewSubsectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertMenuNewSubsectionActionPerformed

    private void InsertMenuNewParagraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMenuNewParagraphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertMenuNewParagraphActionPerformed

    private void UndoMenuSelectedEditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoMenuSelectedEditsActionPerformed
        // TODO add your handling code here:
        System.out.println("hello i am here");
        databaseNoReturnValue(MainUI.connection, "select * from constructs;");
    }//GEN-LAST:event_UndoMenuSelectedEditsActionPerformed

    private void UndoMenuLastChapterEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoMenuLastChapterEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UndoMenuLastChapterEditActionPerformed

    private void DeleteMenuSelectedEditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMenuSelectedEditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMenuSelectedEditsActionPerformed

    private void ComboBoxWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxWordsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBoxWordsActionPerformed
    // custom handler to handle all BACKSPACE and DELETE events in the application
    
    private void FileMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuOpenActionPerformed
        String ingest = null;
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose destination.");
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int returnValue = jfc.showOpenDialog(null);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File f = new File(jfc.getSelectedFile().getAbsolutePath());
            try {
                FileReader read = new FileReader(f);
                Scanner scan = new Scanner(read);
                while (scan.hasNextLine()) {
                    String line = scan.nextLine() + "\n";
                    ingest = ingest + line;
                }
                jTextArea1.setText(ingest);
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_FileMenuOpenActionPerformed
    // custom handler to add actions to BACKSPACE and DELETE keys
    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                System.out.println("backspace pressed");
                break;
            case KeyEvent.VK_DELETE:
                System.out.println("delete pressed");
                break;
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* initialize the database */
         MainUI.connection = DatabaseConnection.getConnection();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxChapters;
    private javax.swing.JComboBox<String> ComboBoxPages;
    private javax.swing.JComboBox<String> ComboBoxParagraphs;
    private javax.swing.JComboBox<String> ComboBoxSections;
    private javax.swing.JComboBox<String> ComboBoxSentences;
    private javax.swing.JComboBox<String> ComboBoxWords;
    private javax.swing.JMenu DeleteMenu;
    private javax.swing.JMenuItem DeleteMenuAllChapterEdits;
    private javax.swing.JMenuItem DeleteMenuAllParagraphEdits;
    private javax.swing.JMenuItem DeleteMenuAllSectionEdits;
    private javax.swing.JMenuItem DeleteMenuAllSentenceEdits;
    private javax.swing.JMenuItem DeleteMenuAllSubsectionEdits;
    private javax.swing.JMenuItem DeleteMenuAllWordEdits;
    private javax.swing.JMenuItem DeleteMenuSelectedEdits;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem FileMenuNew;
    private javax.swing.JMenuItem FileMenuOpen;
    private javax.swing.JMenuItem FileMenuQuit;
    private javax.swing.JMenuItem FileMenuSave;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem HelpMenuFAQ;
    private javax.swing.JMenuItem HelpMenuReportBug;
    private javax.swing.JMenuItem HelpMenuScribrManual;
    private javax.swing.JMenu InsertMenu;
    private javax.swing.JMenuItem InsertMenuNewChapter;
    private javax.swing.JMenuItem InsertMenuNewParagraph;
    private javax.swing.JMenuItem InsertMenuNewSection;
    private javax.swing.JMenuItem InsertMenuNewSubsection;
    private javax.swing.JMenuBar MainMenuBar;
    private javax.swing.JMenu UndoMenu;
    private javax.swing.JMenuItem UndoMenuAllChapterEdits;
    private javax.swing.JMenuItem UndoMenuAllPageEdits;
    private javax.swing.JMenuItem UndoMenuAllParagraphEdits;
    private javax.swing.JMenuItem UndoMenuAllSectionEdits;
    private javax.swing.JMenuItem UndoMenuAllSentenceEdits;
    private javax.swing.JMenuItem UndoMenuAllWordEdits;
    private javax.swing.JMenuItem UndoMenuLastChapterEdit;
    private javax.swing.JMenuItem UndoMenuLastParagraphEdit;
    private javax.swing.JMenuItem UndoMenuLastSectionEdit;
    private javax.swing.JMenuItem UndoMenuLastSentenceEdit;
    private javax.swing.JMenuItem UndoMenuLastSubsectionEdit;
    private javax.swing.JMenuItem UndoMenuLastWordEdit;
    private javax.swing.JMenuItem UndoMenuSelectedEdits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
